import { format } from 'date-fns'
import type { ReportFormat } from '../types'

// PDF Export using browser print API (for client-side generation)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function exportToPDF(title: string, content: string, _filename: string) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    throw new Error('Failed to open print window. Please allow popups.')
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <meta charset="utf-8">
        <style>
          @page {
            size: A4;
            margin: 20mm;
          }
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #333;
            background: white;
          }
          .header {
            border-bottom: 3px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 30px;
          }
          .header h1 {
            font-size: 24pt;
            color: #1e40af;
            margin-bottom: 5px;
          }
          .header .meta {
            color: #666;
            font-size: 9pt;
          }
          .section {
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .section-title {
            font-size: 16pt;
            color: #1e40af;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 5px;
            margin-bottom: 15px;
            margin-top: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            font-size: 10pt;
          }
          th {
            background-color: #2563eb;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: 600;
          }
          td {
            padding: 8px 10px;
            border-bottom: 1px solid #e5e7eb;
          }
          tr:nth-child(even) {
            background-color: #f9fafb;
          }
          .metric-card {
            background: #f3f4f6;
            border-left: 4px solid #2563eb;
            padding: 15px;
            margin: 10px 0;
          }
          .metric-label {
            font-size: 9pt;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .metric-value {
            font-size: 20pt;
            color: #1f2937;
            font-weight: bold;
            margin-top: 5px;
          }
          .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8pt;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
          }
          @media print {
            body {
              print-color-adjust: exact;
              -webkit-print-color-adjust: exact;
            }
            .no-print {
              display: none;
            }
            .page-break {
              page-break-before: always;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <div class="meta">
            Generated: ${format(new Date(), 'PPP p')}<br>
            Organization: Integrated Management System
          </div>
        </div>
        <div class="content">
          ${content}
        </div>
        <div class="footer">
          <p>Confidential - For Internal Use Only | Generated by Integrated Management System</p>
        </div>
      </body>
    </html>
  `)

  printWindow.document.close()

  // Wait for content to load, then print
  setTimeout(() => {
    printWindow.print()
    // Close window after a delay
    setTimeout(() => {
      printWindow.close()
    }, 500)
  }, 500)
}

// DOC Export using HTML to DOC conversion
export function exportToDOC(title: string, content: string, filename: string) {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>${title}</title>
        <style>
          body {
            font-family: 'Calibri', 'Arial', sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #333;
            margin: 40px;
          }
          h1 {
            color: #1e40af;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          h2 {
            color: #1e40af;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 5px;
            margin-top: 25px;
            margin-bottom: 15px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
          }
          th {
            background-color: #2563eb;
            color: white;
            padding: 10px;
            text-align: left;
          }
          td {
            padding: 8px 10px;
            border: 1px solid #e5e7eb;
          }
          tr:nth-child(even) {
            background-color: #f9fafb;
          }
          .metric-card {
            background: #f3f4f6;
            border-left: 4px solid #2563eb;
            padding: 15px;
            margin: 10px 0;
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p><strong>Generated:</strong> ${format(new Date(), 'PPP p')}</p>
        <p><strong>Organization:</strong> Integrated Management System</p>
        <hr>
        ${content}
      </body>
    </html>
  `

  // Convert HTML to DOC format
  const blob = new Blob(
    [
      '\ufeff', // BOM for UTF-8
      htmlContent,
    ],
    { type: 'application/msword;charset=utf-8' }
  )

  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `${filename}_${format(new Date(), 'yyyy-MM-dd')}.doc`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Excel/CSV Export (already exists in dashboard utils, but we'll include here for completeness)
export function exportToCSV(data: Array<Record<string, unknown>>, filename: string) {
  if (data.length === 0) return

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header]
          if (value instanceof Date) {
            return format(value, 'yyyy-MM-dd')
          }
          if (typeof value === 'object' && value !== null) {
            return JSON.stringify(value).replace(/,/g, ';')
          }
          return String(value ?? '').replace(/,/g, ';').replace(/"/g, '""')
        })
        .join(',')
    ),
  ].join('\n')

  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `${filename}_${format(new Date(), 'yyyy-MM-dd')}.csv`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// JSON Export
export function exportToJSON(data: unknown, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonContent], { type: 'application/json;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `${filename}_${format(new Date(), 'yyyy-MM-dd')}.json`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Main export function that routes to the appropriate format
export function exportReport(
  format: ReportFormat,
  title: string,
  content: string,
  data?: Array<Record<string, unknown>>,
  filename?: string
) {
  const reportFilename = filename || title.toLowerCase().replace(/\s+/g, '_')

  switch (format) {
    case 'pdf':
      exportToPDF(title, content, reportFilename)
      break
    case 'doc':
      exportToDOC(title, content, reportFilename)
      break
    case 'csv':
      if (data) {
        exportToCSV(data, reportFilename)
      }
      break
    case 'excel':
      // Excel is same as CSV for now
      if (data) {
        exportToCSV(data, reportFilename)
      }
      break
    default:
      throw new Error(`Unsupported export format: ${format}`)
  }
}

